# Site settings
title: TONY TANG
email: me@tonytang.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nflavour.github.io" # the base hostname & protocol for your site
twitter_username: tonytanger
github_username:  nflavour
youtube_username: nflavour

# Build settings
markdown: kramdown
