# Site settings
title: TONY TANG
email: tonycantang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <strong>Jekyll:</strong> 'Write an awesome description for your new site here.'<br />
  <strong>Tony:</strong> 'It's not awesome enough yet. So the description is going to have to wait'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tonyt.me" # the base hostname & protocol for your site
twitter_username: tonytanger
github_username:  tonytanger
youtube_username: nflavour

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
